### ISSUE TITLE
插件异常

### ISSUE THREAD

**Issue by yolo079** [gclm/gitfox#12]
IDE: CLion
version: Build #CL-222.4345.21

日志如下:
---

java.lang.NullPointerException: Cannot invoke "club.gclmit.plugin.jetbrains.gitfox.model.Gitfox.getItems()" because "gitfox" is null
	at club.gclmit.plugin.jetbrains.gitfox.views.CommitGuidePanel.<init>(CommitGuidePanel.java:40)
	at club.gclmit.plugin.jetbrains.gitfox.views.CommitGuideDialog.<init>(CommitGuideDialog.java:22)
	at club.gclmit.plugin.jetbrains.gitfox.config.CommitGuideAction.actionPerformed(CommitGuideAction.java:43)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:190)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:166)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:840)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by gclm** [comment]
插件版本是？
> 建议你先重置一下服务，看正常不

<img width="798" alt="image" src="https://user-images.githubusercontent.com/27618687/200575189-665f2850-ee1c-4af7-ac15-cc75de42fb3f.png">

**Comment by gclm** [comment]
插件版本是：

**Comment by liaozihang** [comment]
> 
新安装的插件,版本是0.4.1
你提到的这个界面,不知道在那里打开.

**Comment by yolo079** [comment]
> 插件版本是？
> 
> > 建议你先重置一下服务，看正常不
> 
> <img alt="image" width="798" src="https://user-images.githubusercontent.com/27618687/200575189-665f2850-ee1c-4af7-ac15-cc75de42fb3f.png">

新安装的插件,版本是0.4.1
你提到的这个界面,不知道在那里打开.

**Comment by gclm** [comment]
在设置里面，具体情况可以看一下readme 文件。另外插件默认需要再外网使用，内网使用的需要做特殊配置

**Comment by yolo079** [comment]
> 在设置里面，具体情况可以看一下readme 文件。另外插件默认需要再外网使用，内网使用的需要做特殊配置

好的,我先看看说明.麻烦你了.

**Comment by yolo079** [comment]
应该是网络问题,家里使用正常.
